# This file was generated by the {rix} R package v0.16.0 on 2025-10-10
# with following call:
# >rix(r_ver = "eda49fdab2de9361375a998a18e4af20bd7d056d",
#  > r_pkgs = all_packages,
#  > system_pkgs = c("git",
#  > "python3",
#  > "quarto"),
#  > git_pkgs = list(list(package_name = "myTAI",
#  > repo_url = "https://github.com/drostlab/myTAI/",
#  > commit = "656bb16")),
#  > tex_pkgs = c("amsmath"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = "")
# It uses upstream nixpkgs' revision eda49fdab2de9361375a998a18e4af20bd7d056d for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/eda49fdab2de9361375a998a18e4af20bd7d056d.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      BiocManager
      biomartr
      Biostrings
      CoordinateCleaner
      DBI
      dplyr
      duckdb
      geotargets
      ggplot2
      jsonlite
      kableExtra
      knitr
      languageserver
      nodbi
      plotly
      prism
      quarto
      rgbif
      robis
      tarchetypes
      targets
      taxa
      terra
      tidyr
      wikitaxa;
  };
 
    myTAI = (pkgs.rPackages.buildRPackage {
      name = "myTAI";
      src = pkgs.fetchgit {
        url = "https://github.com/drostlab/myTAI/";
        rev = "656bb16";
        sha256 = "sha256-J3OYDjS9h6nOc61uXXDT52Qj85xakYxcXRVcbTLeUjE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          S7
          patchwork
          purrr
          tidyr
          Rcpp
          memoise
          fitdistrplus
          dplyr
          RColorBrewer
          reshape2
          ggplot2
          cowplot
          ggforce
          ggridges
          ggtext
          readr
          tibble
          scales
          ggplotify
          ggrepel
          uwot
          Matrix
          pheatmap
          RcppArmadillo
          RcppThread;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      python3
      quarto
      R
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ myTAI rpkgs tex  system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
