name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("targets", "tarchetypes", "dplyr", "quarto"))'
          R -e 'install.packages(c("robis", "rgbif", "CoordinateCleaner", "terra"))'
      
      - name: Run targets pipeline
        run: |
          Rscript -e 'targets::tar_make()'