name: Deploy Quarto Report to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'reportes/analisis_biodiversidad_marina.html'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Copy HTML to root as index.html
        run: |
          cp reportes/analisis_biodiversidad_marina.html index.html
          echo "✅ Copied HTML file"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4